CREATE TABLE IF NOT EXISTS ns_simpledrugs_xp (
  identifier VARCHAR(64) NOT NULL PRIMARY KEY,
  xp INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
